name: Importar paquete a Appian QA

on:
  workflow_dispatch:
    inputs:
      package_path:
        description: 'Ruta al archivo del paquete exportado (zip en el repo)'
        required: true
      description:
        description: 'Descripción del import (opcional)'
        required: false
      customization_file:
        description: 'Ruta al archivo de customization .properties (opcional)'
        required: false

jobs:
  importar-paquete:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Verificar variables requeridas
        run: |
          if [ -z "${{ vars.URL }}" ]; then
            echo "❌ Error: URL no está definido."
            exit 1
          fi

      - name: Ejecutar importación del paquete en QA
        run: |
          PACKAGE_FILENAME=$(basename "${{ github.event.inputs.package_path }}")
          if [ -n "${{ github.event.inputs.customization_file }}" ]; then
            curl --location --request POST "${{ vars.URL }}/suite/deployment-management/v2/deployments" \
            --header "appian-api-key: ${{ secrets.API_KEY }}" \
            --header "Action-Type: import" \
            --form "json={
              \"name\": \"Imported Package\",
              \"description\": \"${{ github.event.inputs.description }}\",
              \"packageFileName\": \"$PACKAGE_FILENAME\",
              \"customizationFileName\": \"$(basename ${{ github.event.inputs.customization_file }})\"
            }" \
            --form "packageFileName=@${{ github.event.inputs.package_path }}" \
            --form "customizationFileName=@${{ github.event.inputs.customization_file }}"
          else
            curl --location --request POST "${{ vars.URL }}/suite/deployment-management/v2/deployments" \
            --header "appian-api-key: ${{ secrets.API_KEY }}" \
            --header "Action-Type: import" \
            --form "json={
              \"name\": \"Imported Package\",
              \"description\": \"${{ github.event.inputs.description }}\",
              \"packageFileName\": \"$PACKAGE_FILENAME\"
            }" \
            --form "packageFileName=@${{ github.event.inputs.package_path }}"
          fi