name: Inspeccionar paquete o aplicación Appian

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Nombre lógico del paquete o aplicación (correspondiente al nombre del ZIP en deployments/dev)"
        required: true
        type: string
      description:
        description: "Descripción de la inspección"
        required: false
        type: string
      environment_name:
        description: "Nombre del entorno (qa, prod, etc.)"
        required: true
        type: string

  workflow_call:
    inputs:
      package_name:
        description: "Nombre lógico del paquete o aplicación (correspondiente al nombre del ZIP en deployments/dev)"
        required: true
        type: string
      description:
        description: "Descripción de la inspección"
        required: false
        type: string
      environment_name:
        description: "Nombre del entorno (qa, prod, etc.)"
        required: true
        type: string
    secrets:
      API_KEY:
        required: true

jobs:
  inspeccionar:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Descargar artefacto exportado
        uses: actions/download-artifact@v4
        with:
          name: app-${{ inputs.package_name }}
          path: deployments/dev

      - name: Validar URL
        run: |
          if [ -z "${{ vars.URL }}" ]; then
            echo "❌ Error: URL no está definido."
            exit 1
          fi

      - name: Verificar existencia del paquete
        run: |
          echo "Verificando existencia del archivo deployments/dev/${{ inputs.package_name }}.zip"
          if [ ! -f "deployments/dev/${{ inputs.package_name }}.zip" ]; then
            echo "❌ El archivo no existe: deployments/dev/${{ inputs.package_name }}.zip"
            exit 1
          fi

      - name: Ejecutar inspección en Appian en ${{ inputs.environment_name }}
        run: |
          curl --location --request POST "${{ vars.URL }}/suite/deployment-management/v2/inspections" \
          --header "appian-api-key: ${{ secrets.API_KEY }}" \
          --form 'json={
            "packageFileName": "${{ inputs.package_name }}.zip"
          }' \
          --form "packageFileName=@deployments/dev/${{ inputs.package_name }}.zip" \
          --output inspection_response.json

      - name: Verificar respuesta cruda de inspección
        run: |
          echo "🔍 Contenido de inspection_response.json:"
          cat inspection_response.json

      - name: Extraer UUID de la inspección
        id: extract_uuid
        run: |
          inspection_uuid=$(jq -r '.uuid' inspection_response.json)
          echo "UUID de inspección: $inspection_uuid"
          echo "inspection_uuid=$inspection_uuid" >> $GITHUB_OUTPUT

      - name: Consultar resultado de la inspección
        run: |
          status="IN_PROGRESS"
          while [ "$status" == "IN_PROGRESS" ]; do
            sleep 10
            response=$(curl --location --request GET "${{ vars.URL }}/suite/deployment-management/v2/inspections/${{ steps.extract_uuid.outputs.inspection_uuid }}" \
            --header "appian-api-key: ${{ secrets.API_KEY }}")
            status=$(echo $response | jq -r '.status')
            echo "Estado actual de la inspección: $status"
          done
          if [ "$status" != "COMPLETED" ]; then
            echo "La inspección terminó con estado: $status"
            exit 1
          fi

          # Validar si hubo errores de inspección
          total_errors=$(curl --location --request GET "${{ vars.URL }}/suite/deployment-management/v2/inspections/${{ steps.extract_uuid.outputs.inspection_uuid }}" \
            --header "appian-api-key: ${{ secrets.API_KEY }}" | jq -r '.summary.problems.totalErrors')

          echo "Errores encontrados en la inspección: $total_errors"

          if [ "$total_errors" != "0" ]; then
            echo "❌ La inspección contiene errores. Mostrando detalle completo:"
            curl --location --request GET "${{ vars.URL }}/suite/deployment-management/v2/inspections/${{ steps.extract_uuid.outputs.inspection_uuid }}" \
              --header "appian-api-key: ${{ secrets.API_KEY }}" | jq .
            echo "❌ Deteniendo el workflow."
            exit 1
          fi

      - name: Mostrar detalle completo de la inspección
        if: always()
        run: |
          curl --location --request GET "${{ vars.URL }}/suite/deployment-management/v2/inspections/${{ steps.extract_uuid.outputs.inspection_uuid }}" \
          --header "appian-api-key: ${{ secrets.API_KEY }}" | jq .